name: Release Chrome Extension

on:
  push:
    branches: 
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build extension
      run: npm run build
    
    - name: Create ZIP package
      run: |
        mkdir -p dist
        zip -r dist/chrome-extension.zip ./build
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/chrome-extension.zip
        tag_name: v${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
